name: CI

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry (ACR)
        run: az acr login --name metabank

      - name: Prepare Image Tag
        id: prepare-tag
        run: |
          TAG=$(date +%s)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated TAG: $TAG"

      - name: Build and Push Docker Image to Azure ACR
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            metabank.azurecr.io/metanet-msa-migration-fe:latest
            metabank.azurecr.io/metanet-msa-migration-fe:${{ env.TAG }}

      - name: Checkout ArgoCD Repository
        uses: actions/checkout@v3
        with:
          repository: Metanet-Signal-Platoon/ArgoCD-metabank
          token: ${{ secrets.GH_PAT }}
          ref: main  # ✅ 현재 브랜치 체크아웃
          fetch-depth: 0  

      - name: Set Environment Variables Based on Branch
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "VALUES_FILE=argo-metanet-msa-migration-fe-dev/values-dev.yaml" >> $GITHUB_ENV
            echo "APP_FILE=argo-metanet-msa-migration-fe-dev/application.yaml" >> $GITHUB_ENV
            echo "VALUE_FILE_NAME=values-dev.yaml" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "VALUES_FILE=argo-metanet-msa-migration-fe-qa/values-qa.yaml" >> $GITHUB_ENV
            echo "APP_FILE=argo-metanet-msa-migration-fe-qa/application.yaml" >> $GITHUB_ENV
            echo "VALUE_FILE_NAME=values-qa.yaml" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "VALUES_FILE=argo-metanet-msa-migration-fe-prod/values-prod.yaml" >> $GITHUB_ENV
            echo "APP_FILE=argo-metanet-msa-migration-fe-prod/application.yaml" >> $GITHUB_ENV
            echo "VALUE_FILE_NAME=values-prod.yaml" >> $GITHUB_ENV
          else
            echo "Invalid branch. Exiting..."
            exit 1
          fi

      - name: Check File Paths
        run: |
          if [ ! -f "${{ env.VALUES_FILE }}" ]; then
            echo "Error: values.yaml not found at ${{ env.VALUES_FILE }}"
            exit 1
          fi
          if [ ! -f "${{ env.APP_FILE }}" ]; then
            echo "Error: application.yaml not found at ${{ env.APP_FILE }}"
            exit 1
          fi

          echo "Found values file: ${{ env.VALUES_FILE }}"
          echo "Found application file: ${{ env.APP_FILE }}"

      - name: Update Image in Values File
        run: |
          echo "Updating image tag in ${{ env.VALUES_FILE }}"
          sed -i "s|tag: .*|tag: \"${{ env.TAG }}\"|" "${{ env.VALUES_FILE }}"

      - name: Update valueFiles in application.yaml
        run: |
          echo "Updating valueFiles in ${{ env.APP_FILE }}"
          sed -i "s|valueFiles:.*|valueFiles:\\n      - ${{ env.VALUE_FILE_NAME }}|" "${{ env.APP_FILE }}"

          echo "=== Updated application.yaml ==="
          cat "${{ env.APP_FILE }}"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git add "${{ env.VALUES_FILE }}" "${{ env.APP_FILE }}"

          # 변경 사항이 있는 경우에만 푸시
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update image tag and valueFiles to ${{ env.VALUE_FILE_NAME }} in ${{ env.APP_FILE }}"
            git push origin main  # ✅ 현재 브랜치로 푸시
          fi
