name: CI

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry (ACR)
        run: az acr login --name metabank

      - name: Prepare Image Tag
        id: prepare-tag
        run: |
          TAG=$(date +%s)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated TAG: $TAG"

      - name: Build and Push Docker Image to Azure ACR
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            metabank.azurecr.io/metanet-msa-migration-fe:latest
            metabank.azurecr.io/metanet-msa-migration-fe:${{ env.TAG }}

      - name: Checkout ArgoCD Repository
        uses: actions/checkout@v3
        with:
          repository: Metanet-Signal-Platoon/ArgoCD-metabank
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.ref_name }}  # ✅ 현재 브랜치를 체크아웃
          fetch-depth: 0  

      - name: Set Environment Variables Based on Branch
        run: |
          case "${{ github.ref_name }}" in
            "dev")
              echo "VALUES_FILE=argo-metanet-msa-migration-fe-dev/values-dev.yaml" >> $GITHUB_ENV
              ;;
            "qa")
              echo "VALUES_FILE=argo-metanet-msa-migration-fe-qa/values-qa.yaml" >> $GITHUB_ENV
              ;;
            "prod")
              echo "VALUES_FILE=argo-metanet-msa-migration-fe-prod/values-prod.yaml" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid branch. Exiting..."
              exit 1
              ;;
          esac

      - name: Check File Paths
        run: |
          if [ ! -f "${{ env.VALUES_FILE }}" ]; then
            echo "Error: values.yaml not found at ${{ env.VALUES_FILE }}"
            exit 1
          fi

          echo "Found values file: ${{ env.VALUES_FILE }}"

      - name: Update Image in Values File
        run: |
          if [ -f "${{ env.VALUES_FILE }}" ]; then
            echo "Updating image tag in ${{ env.VALUES_FILE }}"
            sed -i "s|tag: .*|tag: \"${{ env.TAG }}\"|" "${{ env.VALUES_FILE }}"
          else
            echo "Error: values file not found!"
            exit 1
          fi

          # 변경 사항 확인
          git diff

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git add "${{ env.VALUES_FILE }}"

          # 변경 사항이 있는 경우에만 푸시
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update image tag to ${{ env.TAG }} in ${{ env.VALUES_FILE }}"
            git push origin ${{ github.ref_name }}  # ✅ 현재 브랜치로 푸시
          fi
