name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Image Tag
        id: prepare-tag
        run: |
          echo "TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ykim73094/metanet-msa-migration-fe:latest
            ykim73094/metanet-msa-migration-fe:${{ env.TAG }}

      - name: Checkout Deployment Repository
        uses: actions/checkout@v3
        with:
          repository: Metanet-Signal-Platoon/argo-test
          token: ${{ secrets.GH_PAT }}

      - name: Update Image
        run: |
          sed -i 's|image: Metanet-Signal-Platoon/argo-test:.*|image: Metanet-Signal-Platoon/metanet-msa-migration-fe:${{ env.TAG }}|g' argo-test/deployment.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update image to ykim73094/metanet-msa-migration-fe:${{ env.TAG }}"
          git push origin master
